name: Testing
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        # with:
        # python-version: '3.10' 
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python first.py
      - name: Run a one-line script
        run: python second.py
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
